services:

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 2

  be-1:
    build:
      context: .
      dockerfile: ./backend-1/Dockerfile
      target: prod
    container_name: be-1
    env_file:
      - .env
    environment:
      - USE_YANDEX=false           # пока выключим, включишь после получения ключа
      - MATCH_RADIUS_KM=30
      - MATCH_MAX_DETOUR_MIN=60
      - MATCH_AVG_SPEED_KMH=60
      - MATCH_WORKER_INTERVAL_SEC=30
      - AUDIT_URL=                 # если есть аудит, укажи URL
      - SEED_POINTS=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BE1_PORT:-8001}:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/health > /dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  be-2-request:
    build:
      context: ./backend-2/Request
      dockerfile: Dockerfile
    container_name: be-2-request
    environment:
      PORT: "8081"
      SERVICE_NAME: "request-service"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "app"
      AUDIT_SERVICE_URL: "http://be-3:8083"
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  be-2-office:
    build:
      context: ./backend-2/Office
      dockerfile: Dockerfile
    container_name: be-2-office
    environment:
      PORT: "8082"
      SERVICE_NAME: "office-service"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "app"
      AUDIT_SERVICE_URL: "http://be-3:8083"
      REQUEST_SERVICE_URL: "http://be-2-request:8081"
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      be-2-request:
        condition: service_started

  be-3:
    build:
      context: ./backend-3
      dockerfile: Dockerfile
    container_name: be-3
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  fe-1:
    build:
      context: ./frontend-1
      dockerfile: Dockerfile
    container_name: fe-1
    env_file:
      - .env

  fe-2:
    build:
      context: ./frontend-2
      dockerfile: Dockerfile
    container_name: fe-2
    env_file:
      - .env

volumes:
  pg_data:

networks:
  default:
    driver: bridge
    enable_ipv6: false