version: '3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ["server"]
    networks:
      - network
    ports:
      - "8080:8080"
      - "50051:50051"
      - "40000:40000"
    expose:
      - "8080"
      - "50051"
    volumes:
      - .:/app
    env_file:
      - .env
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ["worker"]
    networks:
      - network
    ports:
      - "40001:40000"
    volumes:
      - .:/app
    env_file:
      - .env
  database:
    container_name: database
    image: mysql:8
    restart: always
    networks:
      - network
    volumes:
      - database_data:/var/lib/mysql
    env_file:
      - .env
  pubsub:
    container_name: pubsub
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:434.0.0-emulators
    command: "gcloud beta emulators pubsub start --host-port=0.0.0.0:8085"
    restart: always
    networks:
      - network
    ports:
      - "8085:8085"
    expose:
      - "8085"
    env_file:
      - .env

volumes:
  database_data:
    driver: local

networks:
  network:
    driver: bridge
